// Die 14 produktneutralen Standard-Einwände des Einwand-Trainers.
//
// Historie: der Einwand-Trainer war früher eine eigenständige HTML-Datei in
// public/tools/, die in einem iframe lief — dadurch kannte er das Design der
// Academy nicht (eigene Farben, eigene Schrift, kein Hell/Dunkel). Er ist
// jetzt eine normale Seite der App; diese Liste ist unverändert übernommen.
//
// Organisationen können eigene Einwände ergänzen (Tabelle custom_objections,
// siehe pages/admin/objections.js) — die werden zur Laufzeit dazugemischt.
// "cat" verweist auf denselben Kategorie-Schlüssel wie die Einwand-Kategorien
// des Call Trackers (siehe lib/objectionCategories.js).
export const DEFAULT_OBJECTIONS = [
    { id:1, cat:"preis",
      q_pro:`„Ich bin sowieso schon gut ausgelastet, ich brauche gerade nichts Neues.“`,
      a_pro:`Das freut mich für Sie — viele wären froh, so gut ausgelastet zu sein. Darf ich fragen: ist das schon länger so, oder gerade nur saisonal viel los? Wenn's schon immer so ist: genau dann lohnt sich unser Angebot am meisten — Sie können sich dann die besten Kunden aussuchen, statt jede Anfrage anzunehmen. Wenn's saisonal ist: dann macht's erst recht Sinn, jetzt vorzusorgen, damit es auch in ruhigeren Phasen weiterläuft.`,
      q_ent:`„Bin eh voll ausgelastet, brauch grad nix Neues.“`,
      a_ent:`Cool, läuft bei dir richtig gut. Ist das schon immer so oder grad nur viel los? Wenn's immer so ist: genau dann lohnt sich unser Angebot am meisten — du kannst dir dann die besten Kunden aussuchen. Wenn's saisonal ist: dann lohnt's sich erst recht, jetzt für die ruhigeren Phasen vorzusorgen.`,
      tip:`Nie die Auslastung anzweifeln — auf Auswahl/Zukunftssicherung umlenken.` },
    { id:2, cat:"preis",
      q_pro:`„Das ist mir zu teuer.“`,
      a_pro:`Verstehe ich total. Deswegen ist das Ganze auch risikofrei aufgebaut: Sie sehen zuerst, was Sie bekommen, und entscheiden sich erst danach. Sie verlieren nichts außer ein paar Minuten Zeit.`,
      q_ent:`„Ist mir zu teuer.“`,
      a_ent:`Versteh ich. Deswegen ist's ja auch risikofrei — du siehst erst, was du bekommst, und entscheidest dich danach. Du verlierst nix außer ein paar Minuten.`,
      tip:`Preis nie verteidigen — auf das geringe Risiko des ersten Schritts zurücklenken.` },
    { id:3, cat:"skepsis",
      q_pro:`„Was ist der Haken — warum sollten Sie mir das anbieten, wenn's Ihnen am Ende nichts bringt?“`,
      a_pro:`Verständliche Frage. Der Haken ist: wir gehen in Vorleistung, weil wir überzeugt sind, dass unser Angebot überzeugt. Passt es am Ende nicht für Sie, war das unsere Zeit, nicht Ihre — genau das ist unser Anreiz, wirklich gute Arbeit abzuliefern.`,
      q_ent:`„Was ist der Haken, wieso solltest du das machen, wenn's dir nix bringt?“`,
      a_ent:`Faire Frage. Der Haken ist: wir gehen in Vorleistung, weil wir wissen, dass unser Angebot überzeugt. Passt's am Ende nicht, war's unsere Zeit, nicht deine — genau deswegen liefern wir auch wirklich gute Arbeit ab.`,
      tip:`Transparenz schlägt Rechtfertigung — das Risiko liegt bewusst bei euch, nicht beim Lead.` },
    { id:4, cat:"skepsis",
      q_pro:`„Woher haben Sie meine Nummer, wie kommen Sie auf mich?“`,
      a_pro:`Ganz einfach: ich habe recherchiert, wer in Ihrer Branche und Region aktiv ist, und Sie sind mir positiv aufgefallen. Deswegen der Anruf — bei einem bestimmten Punkt sehe ich noch Potenzial für Sie.`,
      q_ent:`„Woher hast du meine Nummer?“`,
      a_ent:`Ganz easy, hab recherchiert, wer in deiner Branche und Region aktiv ist, da bist du mir positiv aufgefallen. Deswegen der Anruf — da seh ich noch Potenzial für dich.`,
      tip:`Kurz, ehrlich, direkt zurück zum Nutzen.` },
    { id:5, cat:"skepsis",
      q_pro:`„Ich hatte schon mal eine schlechte Erfahrung mit einem ähnlichen Anbieter.“`,
      a_pro:`Das tut mir leid, das kommt leider öfter vor. Was genau ist da schiefgelaufen? Bei uns tragen Sie ohnehin kaum Risiko, weil Sie sich das Ergebnis erst ansehen, bevor Sie sich entscheiden — böse Überraschungen fallen damit weitgehend weg.`,
      q_ent:`„Hatte schon mal 'ne miese Erfahrung mit 'nem ähnlichen Anbieter.“`,
      a_ent:`Tut mir leid, hört man leider öfter. Was ist denn schiefgelaufen? Bei uns trägst du eh kaum Risiko, weil du dir das Ergebnis erst ansiehst, bevor du dich entscheidest — böse Überraschungen fallen damit weitgehend weg.`,
      tip:`Erst zuhören, dann den Unterschied zum eigenen risikoarmen Modell ziehen.` },
    { id:6, cat:"vorhanden",
      q_pro:`„Ich habe dafür schon eine Lösung.“`,
      a_pro:`Gut zu wissen — dann geht's nur noch um die Frage, ob sie wirklich noch zeitgemäß ist und das volle Potenzial ausschöpft. Genau das schauen wir uns gemeinsam an — passt eh schon alles, ändert sich für Sie nichts; wenn nicht, sehen Sie schwarz auf weiß den Unterschied.`,
      q_ent:`„Hab dafür schon was.“`,
      a_ent:`Gut zu wissen — dann geht's nur noch drum, ob's wirklich noch zeitgemäß ist und das volle Potenzial rausholt. Genau das schauen wir uns an — passt eh alles, ändert sich nix für dich, wenn nicht, siehst du den Unterschied schwarz auf weiß.`,
      tip:`Bestehende Lösung nie schlechtmachen — auf einen konkreten Vergleich verweisen.` },
    { id:7, cat:"vorhanden",
      q_pro:`„Ich habe schon jemanden, der sich darum kümmert.“`,
      a_pro:`Schön, dass Sie sich schon kümmern. Wie zufrieden sind Sie mit dem Ergebnis, merken Sie das auch am Erfolg? Ein Vergleich kostet Sie nichts, schaden kann er also nicht.`,
      q_ent:`„Hab schon wen, der sich drum kümmert.“`,
      a_ent:`Schön, kümmerst du dich schon drum. Bist du zufrieden, merkst du das am Erfolg? Ein Vergleich kostet dich nix, schaden kann er also nicht.`,
      tip:`Nie gegen bestehenden Dienstleister schießen — Ergebnis hinterfragen.` },
    { id:8, cat:"zeit",
      q_pro:`„Ich habe gerade keine Zeit.“`,
      a_pro:`Verstehe, deswegen dauert der Termin auch bewusst nur wenige Minuten, und Sie müssen sich auf gar nichts vorbereiten. Passt es Ihnen eher [Tag A] oder [Tag B]?`,
      q_ent:`„Grad keine Zeit.“`,
      a_ent:`Kein Ding, dauert eh nur ein paar Minuten, musst dich auf nix vorbereiten. Passt dir [Tag A] oder [Tag B] besser?`,
      tip:`Kürze betonen, dann direkt zurück zur Terminfrage.` },
    { id:9, cat:"zeit",
      q_pro:`„Schicken Sie mir das per E-Mail/WhatsApp.“`,
      a_pro:`Mache ich gerne zusätzlich, aber die Details zeigen sich erst richtig im gemeinsamen Gespräch — da können wir auch direkt auf Ihre Fragen eingehen. Passt Ihnen eher [Tag A] oder [Tag B] für ein paar Minuten?`,
      q_ent:`„Schick mir das per WhatsApp.“`,
      a_ent:`Mach ich dir gerne zusätzlich, aber am besten zeigt sich das live, da können wir auch gleich Fragen klären. Passt dir [Tag A] oder [Tag B]?`,
      tip:`E-Mail-Wunsch ist meist ein sanftes Nein — freundlich zurück zum Termin lenken.` },
    { id:10, cat:"zeit",
      q_pro:`„Rufen Sie mich in ein paar Wochen nochmal an.“`,
      a_pro:`Mache ich gerne — bis dahin verändert sich an Ihrer aktuellen Situation aber nichts. Wenn wir uns das jetzt kurz gemeinsam anschauen, wissen Sie wenigstens, wo Sie stehen, ganz unverbindlich.`,
      q_ent:`„Meld dich in 'n paar Wochen nochmal.“`,
      a_ent:`Mach ich, aber bis dahin ändert sich bei dir nix. Lass uns das lieber jetzt kurz anschauen, dann weißt du wenigstens, wo du stehst — ganz unverbindlich.`,
      tip:`Aufschub-Kosten benennen, dann Termin trotzdem anbieten.` },
    { id:11, cat:"zeit",
      q_pro:`„Können wir das nicht einfach gleich jetzt machen?“`,
      a_pro:`Das würde ich liebend gern, aber Ihr Angebot wird extra individuell für Sie vorbereitet — dafür brauchen wir ein kleines Zeitfenster. Passt es Ihnen daher eher [nächstmöglicher Slot] oder lieber [späterer Termin]?`,
      q_ent:`„Können wir das nicht einfach gleich jetzt machen?“`,
      a_ent:`Würd ich liebend gern, aber dein Angebot wird extra für dich vorbereitet, dafür brauchen wir ein kleines Zeitfenster. Passt dir eher [nächstmöglicher Slot] oder [späterer Termin]?`,
      tip:`Nie sofort anbieten — die 6-Stunden-Regel gilt auch bei Drängen.` },
    { id:12, cat:"entscheidung",
      q_pro:`„Ich muss das erst mit meinem Partner/meiner Partnerin besprechen.“`,
      a_pro:`Absolut nachvollziehbar. Wäre es sinnvoll, wenn er/sie beim Termin gleich mit dabei ist, damit alle Fragen direkt geklärt sind?`,
      q_ent:`„Muss ich erst mit meinem Partner besprechen.“`,
      a_ent:`Klar, macht Sinn. Wäre es einfach, wenn er/sie beim Termin mit dabei ist? Dann ist das direkt geklärt.`,
      tip:`Partner aktiv in den Termin einladen statt Einwand nur zu akzeptieren.` },
    { id:13, cat:"entscheidung",
      q_pro:`„Ich glaube nicht, dass ich sowas brauche — bei uns lief's bisher auch so gut.“`,
      a_pro:`Das ist bei vielen tatsächlich lange gut gegangen. Trotzdem merken die meisten irgendwann, dass zusätzliche Unterstützung den Unterschied macht — unser Angebot ergänzt das, was bisher funktioniert hat, es ersetzt es nicht.`,
      q_ent:`„Glaub nicht, dass ich sowas brauch, lief bisher auch so gut.“`,
      a_ent:`Ist bei vielen tatsächlich lange gut gegangen. Trotzdem merken die meisten irgendwann, dass ein bisschen Unterstützung den Unterschied macht — unser Angebot ergänzt das, was schon funktioniert, ersetzt es nicht.`,
      tip:`Bestehenden Erfolg nie kleinreden — als Ergänzung positionieren, nicht als Konkurrenz.` },
    { id:14, cat:"entscheidung",
      q_pro:`„Ich muss erst überlegen.“`,
      a_pro:`Klar, das ist keine spontane Entscheidung. Was macht Sie konkret noch unsicher — der Nutzen, der Preis, oder eher der Zeitpunkt? Dann kann ich gezielt darauf eingehen.`,
      q_ent:`„Muss ich erst überlegen.“`,
      a_ent:`Klar, keine spontane Sache. Was macht dich noch unsicher — Nutzen, Preis oder Timing? Dann reden wir gezielt darüber.`,
      tip:`'Überlegen' konkretisieren lassen, dann gezielt behandeln.` }
];
